#backend/gateway/graphql-bff/Cargo.toml

[package]
name = "graphql-bff"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = {workspace = true}
axum = { workspace = true }
tower-http = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true}