# Cargo.toml

[workspace]
members = [
    "backend/services/account/outbox-processor",
    "backend/services/account/cache-invalidator",
    "backend/services/profile/outbox-processor",
    "backend/services/profile/cache-invalidator",
    "crates/account",
    "crates/profile",
    "crates/shared-kernel",
    "crates/gamification",
    "backend/services/profile/query-server"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Wynn <wynn.cn666@gmail.com>"]
repository = "https://github.com/ton-repo/projet"
description = "core-platform repo"

[workspace.dependencies]
# Internes
shared-kernel = { path = "crates/shared-kernel" }
account = { path = "crates/account" }
profile = { path = "crates/profile" }

# Communs
tokio = { version = "1.40", features = ["rt-multi-thread", "macros", "time", "sync", "net", "signal"] }
tokio-util = { version = "0.7.18" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.4"
uuid = { version = "1.19", features = ["v7", "serde"] }
async-trait = "0.1.89"
thiserror = "2.0.17"
anyhow = "1.0"
futures = "0.3.31"
futures-util = "0.3"
rand = "0.9.2"
url = "2.5.7"


# Observabilit√©
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
log = "0.4"

# Infrastructure
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
fred = { version = "10.1.0", features = ["serde-json", "dynamic-pool"] }
rdkafka = "0.38.0"
dashmap = "7.0.0-rc2"
elasticsearch = "9.1.0-alpha.1"

# Utils
regex = "1.12"
lazy_static = "1.5"
seahash = "4.1"
unicode-normalization = "0.1.25"

# Proto / gRPC
tonic = { version = "0.12.3", features = ["codegen", "prost"] }
prost = "0.13.5"
prost-types = "0.13.5"
#tonic-prost = "0.14"
#tonic-prost-build = "0.14"