#backend/services/profile/api/command-server/Cargo.toml

[package]
name = "profile-command-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
# On active spécifiquement les capacités de recherche (ES + gRPC)
shared-kernel = { workspace = true, features = ["service-search", "scylla"] }
profile = { workspace = true }

# Dépendances externes nécessaires au binaire
tokio = { workspace = true }
tonic = { workspace = true }
tonic-health = {workspace = true}