[package]
name = "identity-service"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
identity-proto = { path = "../../../proto/identity/v1" }
identity-lib = { path = "../../../crates/identity" }


tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

sqlx = { workspace = true }
uuid = { workspace = true }
argon2 = { workspace = true }
chrono = { workspace = true }