[package]
name = "account-outbox-processor"
version.workspace = true
edition.workspace = true

[dependencies]
shared-kernel = { workspace = true, features = ["service-outbox"] }
tokio = { workspace = true }