#backend/services/account/cache-invalidator/Cargo.toml

[package]
name = "account-cache-invalidator"
version.workspace = true
edition.workspace = true

[dependencies]
shared-kernel = { workspace = true, features = ["service-invalidator"] }
tokio = { workspace = true }