[package]
name = "profile"
version.workspace = true
edition.workspace = true

[dependencies]
shared-kernel = { workspace = true, features = ["postgres", "concurrency", "runtime"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
scylla = "1.4" # Spécifique au stockage haute fréquence des profils