# crates/profile/Cargo.toml

[package]
name = "profile"
version.workspace = true
edition.workspace = true

[dependencies]
shared-kernel = { workspace = true, features = ["postgres", "elasticsearch", "concurrency", "runtime", "test-utils"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
elasticsearch = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
scylla = { workspace = true }

prost = { workspace = true }
tonic = { workspace = true }
prost-types = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true}
tonic-prost-build = { workspace = true }

[dev-dependencies]
tokio ={ workspace = true }
sqlx = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
mockall = { workspace = true }
futures = {workspace = true}