#  manifests/postgres-external-secret.yaml

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-credentials # C'est le nom du secret final dans K8s
    creationPolicy: Owner
  data:
    - secretKey: DB_URL # La clé qui sera créée dans le secret K8s
      remoteRef:
        key: core-platform/dev/profile-service/db-url # Le NOM de ton secret dans AWS
    - secretKey: SCYLLA_URL
      remoteRef:
        key: core-platform/dev/profile-service/scylla-url