# crates/account/Cargo.toml

[package]
name = "account"
version.workspace = true
edition.workspace = true

[dependencies]
shared-kernel = { workspace = true, features = ["postgres", "runtime", "test-utils"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
regex = { workspace = true }
unicode-normalization = { workspace = true }
idna = { workspace = true }
seahash = { workspace = true }


[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }