# crates/shared-kernel/Cargo.toml

[package]
name = "shared-kernel"
version.workspace = true
edition.workspace = true

[features]
default = []

# --- 1. Drivers Techniques ---
postgres = ["dep:sqlx"]
scylla = ["dep:scylla"]
redis = ["dep:fred"]
kafka = ["dep:rdkafka"]
elasticsearch = ["dep:elasticsearch"]
grpc = []
concurrency = ["dep:dashmap", "dep:futures"]

# --- 2. Capacités Techniques ---
runtime = [
    "tokio/rt",
    "tokio/time",
    "tokio/sync",
    "dep:tokio-util",
    "dep:tracing-subscriber",
    "dep:futures"
]

# --- 3. Rôles Fonctionnels ---
service-api         = ["postgres", "redis", "grpc", "runtime"]
service-outbox      = ["postgres", "kafka", "runtime"]
service-worker      = ["kafka", "runtime", "dep:dashmap"]
service-invalidator = ["redis", "kafka", "runtime", "dep:dashmap"]
service-search = ["elasticsearch", "grpc", "runtime"]
service-projection = ["elasticsearch", "kafka", "runtime"]

[dependencies]
# --- Toujours inclus (Core) ---
uuid = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
rand = { workspace = true }

# OBLIGATOIRES (Pour que Bazel génère les cibles @crates//:tonic)
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

# --- Optionnels (activés par dep: dans les features) ---
sqlx = { workspace = true, optional = true }
fred = { workspace = true, optional = true }
scylla = { workspace = true, optional = true }
rdkafka = { workspace = true, optional = true }
elasticsearch = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true, features = ["rt"] }
tracing-subscriber = { workspace = true, optional = true, features = ["fmt", "env-filter"] }

# --- Utils (Core) ---
futures-util = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
seahash = { workspace = true }
unicode-normalization = { workspace = true }
dyn-clone = { workspace = true}
