#  .github/workflows/gateway-bff-deploy.yml

name: Deploy Gateway BFF

on:
  push:
    paths:
      - 'backend/gateway/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Correction pour Ubuntu 24.04 : Installation de libtinfo5 depuis les dépôts officiels de sécurité
      - name: Install libtinfo5
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt-get install -y ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          rm libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      # Exécution du build et du push vers AWS
      - name: Bazel Build and Push
        run: |
          SHA_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          bazel run --config=ci //backend/gateway/graphql-bff:graphql_bff_push \
          --@rules_oci//oci:remote_tag=$SHA_TAG