#  .github/workflows/profile-service-deploy.yml

name: Deploy Profile Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/services/profile/**'
      - 'infrastructure/live/dev/us-east-1/services/microservices/profile-service/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libtinfo5
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt-get install -y ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          rm libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Bazel Build and Push
        run: |
          bazel run --config=ci//backend/services/profile/api/command-server:profile_command_server_push